---
- name: "Install certbot"
  apt:
    name: certbot
    state: latest
    update_cache: yes

- name: "Install jq dependency for shell script"
  apt:
    name: jq
    state: latest
    update_cache: yes

- name: "Create a directory to store shell script to generate certificate"
  ansible.builtin.file:
    path: "/etc/certificate_generation"
    state: "directory"
    mode: "0755"

- name: "Copy certbot dns hook"
  copy:
    src: "{{ certbot_dns_hook_path }}"
    dest: "/etc/certificate_generation/certbot-dns-hook.sh"
    mode: "u=rwx,g=r,o=r"

- name: "Generate wildcard certificates"
  vars:
    - list_of_present_domains: '{{ hosted_domains|selectattr("state", "equalto", "present")|map(attribute="domain")|list }}'
    - list_of_present_domains_with_wildcard: '{{ list_of_present_domains + list_of_present_domains|map("regex_replace", "^(.*)$", "*.$1")|list}}'
  shell: 'certbot certonly \
    --manual \
    --preferred-challenges=dns \
    --email={{ domain_admin_email }} \
    --agree-tos \
    --domains {{ list_of_present_domains_with_wildcard|join(",") }} \
    --keep-until-expiring \
    --force-renewal \
    --non-interactive \
    --manual-auth-hook="/etc/certificate_generation/certbot-dns-hook.sh create_record {{ api_key }}" \
    --manual-cleanup-hook="/etc/certificate_generation/certbot-dns-hook.sh remove_record {{ api_key }}"' 
