---
- name: "Install certbot"
  apt:
    name: certbot
    state: latest
    update_cache: yes

- name: "Install jq package"
  apt:
    name: jq
    state: latest
    update_cache: yes

- name: "Create a directory to store shell script to generate certificate"
  ansible.builtin.file:
    path: "/etc/certificate_generation"
    state: "directory"
    mode: "0755"

- name: "Copy certbot dns hook"
  copy:
    src: "{{ certbot_dns_hook_path }}"
    dest: "/etc/certificate_generation/certbot-dns-hook.sh"
    mode: "u=rwx,g=rwx,o=r"

- name: "Generate certificate"
  shell: 'certbot certonly \
    --manual \
    --cert-name {{ item.full_url }} \
    --preferred-challenges=dns \
    --email={{ domain_admin_email }} \
    --agree-tos \
    --domains {{ item.full_url }}, www.{{ item.full_url }} \
    --non-interactive \
    --manual-auth-hook="/etc/certificate_generation/certbot-dns-hook.sh create_record {{ api_key }} {{ item.core_domain }}" \
    --manual-cleanup-hook="/etc/certificate_generation/certbot-dns-hook.sh remove_record {{ api_key }} {{ item.core_domain }}"'
  loop: "{{ hosted_domains | selectattr('state', 'equalto', 'present') | list }}"
  
